---
title: "Chapter 2 Solution"
output: html_notebook
---

2.4 Exercises

1.

(a) A flexible method will be better because they fit model when we have large amount of available data. 

(b) A flexible approach will produce worst result because one of its disadvantage is it does not work well with small observations

(c) A flexible approach will produce better fit because the relationship is non-linear. If the relationship is linear , then inflexible methods may fit better.

(d) A Flexible method produce worst result. As a general rule, as we use more flexible methods, the variance will increase and the bias will decrease .

2.

(a) This is Regression probelm since we are working on Quantitative. The goal here is inference not prediction.
    * n =500 firms in the US  
    * p= rofit, number of employees, industry and the CEO    salary.

(b) This is classification and prediction probelm .
    * n = 20 Similar products that were previously launched.  
    * p= price charged for the product, marketing budget, competition price, and ten other variables.


(c) This is Regression and prediction probelm .
    * n = All the weekly data in 2012 
    * p= % change in the US market, the % change in the British market, and the % change in the German market.


4.

(a) A doctor in a hospital want find which disease a patient is suffering from. 
    * This is classification and Inference
    * response : type of the disease
    * Predictors : blood sample , Urine sample etc 
(b) Student Graduation Status
    * This is classification and inference
    * response : First Class , Second Class , Pass 
    * Predictors : Exam grade , Test grade , Assigment grade 

 (c) Election result 
    * This is classification and prediction
    * response : Win , Fail 
    * Predictors : political record , money , honesty , literacy


